{{- if .Values.app.applicationGenericSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := default dict .Values.app.applicationGenericSecrets }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end -}}
